#825 - Add find_target_device_by_pid utility method to the SupernovaI3CBlockingInterface class
binhollc/SupernovaController pull request #21
Opened 2024-01-31 17:14 UTC by Salonso1602

# Resolves  
[825](https://focusuy.atlassian.net/browse/BMC2-825)  

# How to test  
- Plug in Supernova (with 2.0.0 fw)  
- Plug in ICM42605 I3C target
- run examples: (recommended to plug and unplug supernova between executions)  
    - Basic I3C
    - IBI
    - ICM42605

# What to expect  
### basic i3c  
```
Opening Supernova host adapter device and getting access to the I3C protocol interface...
Initializing the bus...

Targets in the I3C bus: {'static_address': 0, 'dynamic_address': 8, 'bcr': 39, 'dcr': 160, 'pid': ['0x00', '0x00', '0x00', '0x00', '0x6a', '0x04']}
Target address: 8 

CCC Transfers
GETPID: [4, 106, 0, 0, 0, 0] 

GETBCR: 27 

GETDCR: A0 

GETCAPS (Get Capabilities): None 

GETMXDS (Get Max Data Speed): None 

GETMRL (Get Max Read Length): 16

UNICAST SETMRL (Set Max Read Length) in: 256 

GETMRL: 256

GETMWL (Get Max Write Length): 8 

BROADCAST SETMWL (Set Max Write Length) in: 128

GETMWL: 128

Write/Read transfers
Write [64] in subaddress 22
Read from subaddress 22: [64]

Write [222, 173, 190, 239] in subaddress 22
Read from subaddress 22: [222, 173, 190, 239]

Reset bus
Resetting bus...
Targets in the I3C bus: []  
```

### IBI  
```
{'static_address': 0, 'dynamic_address': 8, 'bcr': 39, 'dcr': 160, 'pid': ['0x00', '0x00', '0x00', '0x00', '0x6a', '0x04']}
[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

###   ICM42605  
```
{'static_address': 0, 'dynamic_address': 8, 'bcr': 39, 'dcr': 160, 'pid': ['0x00', '0x00', '0x00', '0x00', '0x6a', '0x04']}
Who Am I Register:  [66]
Power Management Register:  [0]
Power Management Register written.
Gyro Config Register:  [6]
Gyro Config Register written.
Status Register:  [0]  
... *Returns a bunch of values  

```

2024-02-13 21:46 UTC, gusaaaaa submitted a review, later dismissed
Good work. Let's add some specs to tests.

2024-03-01 21:54 UTC, pons93 requested changes
Nice and elegant job!!!

I just left a comment regarding the no longer necessity for reversing the PID.

2024-03-01 21:54 UTC, pons93 commented on examples/basic_i3c_example.py
>      target_pid = [0x00, 0x00, 0x00, 0x00, 0x6A, 0x04]
This `target_pid` is reversed. The correct pid for the ICM42605 is [04-6A-00-00-00-00].

2024-03-01 21:54 UTC, pons93 commented on examples/ICM42605_i3c_example.py
>      target_pid = [0x00, 0x00, 0x00, 0x00, 0x6A, 0x04]
This `target_pid` is reversed. The correct pid for the ICM42605 is [04-6A-00-00-00-00].

2024-03-01 21:54 UTC, pons93 commented on examples/ibi_example.py
>      target_pid = [0x00, 0x00, 0x00, 0x00, 0x6A, 0x04]
This `target_pid` is reversed. The correct pid for the ICM42605 is [04-6A-00-00-00-00].

2024-03-01 21:54 UTC, pons93 commented on supernovacontroller/sequential/i3c.py
> +        filtered_devices = list(filter(lambda device: device["pid"][::-1] == pid, responses[0]["table"]))
The reversion of this PID is not longer necessary for new SDK 2.X.X series.

2024-03-01 21:54 UTC, pons93 commented on supernovacontroller/sequential/i3c.py
> +        pid = target_info["pid"][::-1] # Reversing using list slicing
The reversion of this PID is not longer necessary for new SDK 2.X.X series.

2024-03-12 17:11 UTC, pons93 approved these changes
LGTM!!!!!

Just remember that `SupernovaController` v1.1.0 was already released and v1.2.0 is about to be released. Maybe consider to changing base to develop-1.3.0.

2024-03-13 11:51 UTC, Salonso1602 commented
> LGTM!!!!!
> 
> Just remember that `SupernovaController` v1.1.0 was already released and v1.2.0 is about to be released. Maybe consider to changing base to develop-1.3.0.

Done!

2024-05-22 20:48 UTC, merged