#861 - Integrate simulators package and SNController
binhollc/SupernovaController pull request #32
Opened 2024-03-20 03:03 UTC by pons93

Resolves [861](https://focusuy.atlassian.net/browse/BMC2-861).

2024-03-21 13:54 UTC, gusaaaaa requested changes
Other than the issue with the statement that imports the BinhoSimulators in the setup file, it looks good to me in general.

2024-03-21 13:54 UTC, gusaaaaa commented on setup.py
> +      'BinhoSimulators @ git+https://${GH_TOKEN}@github.com/binhollc/BinhoSimulators.git@develop-0.1.0'
```suggestion
      f'BinhoSimulators @ git+https://{gh_token}@github.com/binhollc/BinhoSimulators.git@develop-0.1.0'
```

2024-03-25 11:59 UTC, Salonso1602 requested changes

2024-03-25 11:59 UTC, Salonso1602 commented on supernovacontroller/sequential/supernova_device.py
> -        if supernova_response:
Are we sure we want this to change here and not on the simulator side?

2024-03-25 20:37 UTC, gusaaaaa approved these changes

2024-03-25 20:37 UTC, merged