1.4.0
binhollc/SupernovaController pull request #62
Opened 2024-08-08 19:33 UTC by Salonso1602

# References  
- [Jira Release](https://focusuy.atlassian.net/projects/BMC2/versions/10334/tab/release-report-all-issues)  

# Changes

- [BMC2-1237](https://focusuy.atlassian.net/browse/BMC2-1237)  Integrate GPIO Functionality into SupernovaController

- [BMC2-1275](https://focusuy.atlassian.net/browse/BMC2-1275) Integrate I3C Target Reset Pattern command support in SupernovaController

- [BMC2-1377](https://focusuy.atlassian.net/browse/BMC2-1377) Change name of hot\_join\_example.py to i3c\_hot\_join\_example.py

- [BMC2-1380](https://focusuy.atlassian.net/browse/BMC2-1380) Create tests for testing UART with a real Supernova in SupernovaController

- [BMC2-1402](https://focusuy.atlassian.net/browse/BMC2-1402) Replace the use of hardcoded port addresses in all SupernovaController examples by the use of openAllConnectedSupernovaDevices\(\) method

- [BMC2-1403](https://focusuy.atlassian.net/browse/BMC2-1403) Increase consistency in SupernovaController's README.md regarding nomenclature when referring to supernova as target

- [BMC2-1473](https://focusuy.atlassian.net/browse/BMC2-1473) Fix wrong frequency variable passed to openDrainRate argument in all I3C methods

- [BMC2-1517](https://focusuy.atlassian.net/browse/BMC2-1517) Remove target\_address argument from i3cRSTDAA function

- [BMC2-1518](https://focusuy.atlassian.net/browse/BMC2-1518) Add missing events argument to enec and disec methods

# Bug Fixes

- [BMC2-1418](https://focusuy.atlassian.net/browse/BMC2-1418) Update static methods with the built in python wrapper in SNController 

- [BMC2-1463](https://focusuy.atlassian.net/browse/BMC2-1463) Update Customer Support Email in SNController

# How to Test  
**TBD**

2024-08-09 19:12 UTC, pons93 approved these changes
LGTM!!!!!!

Comment: I run the suggested test + all the rest of the examples running all of them as expected!!!!

We are almost there!!!!!

2024-08-12 16:24 UTC, gusaaaaa requested changes

2024-08-12 16:24 UTC, gusaaaaa commented on README.md
> +    ```
I don't see in the example where `gpio_interrupt_event` is set. I think part of the logic is missing here, the one related with `on_notification`.

2024-08-12 17:27 UTC, gusaaaaa commented on supernovacontroller/sequential/gpio.py
> +        return (response_success, "Success" if response_success else "Configuration failed, error from the Supernova")
```suggestion
        if not response_success:
            return (False, "Configuration failed, error from the Supernova")
            
            self.configured_pins[pin_number] = functionality
            return (True, "Success") # or (True, None)
```

2024-08-12 17:29 UTC, gusaaaaa commented on supernovacontroller/sequential/gpio.py
> +        return (False, "Digital read failed, error from the Supernova")
In general, it's a good practice to first check for error values and break the flow, and then continue with the "happy path".

2024-08-12 17:35 UTC, gusaaaaa commented on supernovacontroller/sequential/gpio.py
- When wrapping SDK commands that don't return any value, instead of returning (True, "Success"), return (True, None) for consistency with the rest of the API.
- Early return. It's a good practice to check for errors or special conditions first, and allow the "happy path" of the logic to proceed afterwards. See inline comment.

2024-08-13 16:04 UTC, gusaaaaa approved these changes
Great job! Congratulations team! 🥳

2024-08-13 16:12 UTC, merged